---
title: "Licencia de código abierto"
---

{{< include ./html/_translate_button.qmd >}}

{{< include ./html/_link_out.qmd >}}

El código fuente de esta página se publica bajo una licencia internacional [GNU GPL v2](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html). La sociedad necesita que la investigación y la ciencia sean gratuitas, abiertas y transparentes. La reproducibilidad, el intercambio libre de conocimiento y la igualdad de condiciones al reducir los costos son fundamentales para responder a los desafíos actuales.

Las siguientes licencias se aplican al texto, las imágenes, el código y los datos de este blog. Mi objetivo es minimizar los obstáculos legales a la difusión, el intercambio, el uso y la reutilización de este trabajo. Sin embargo, los derechos existentes de los autores cuya obra se cita están reservados a dichos autores.

-   [GNU GPL v2](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html) para el código
-   [CC0](https://wiki.creativecommons.org/wiki/CC0_use_for_data) para los datos
-   [Unsplash](https://unsplash.com/es/licencia) para las imágenes. Trato siempre de agregar una marca con el autor.

::: {.callout-note appearance="simple"}
## Importante

{{< fa brands github >}} Puedes encontrar el código de fuente en el siguiente enlace: JDC_website

{{< include ./html/_coffe_button.qmd >}}
:::

::: center
{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}}
:::